
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'bq_dbt_training'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'bq_dbt_training'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  bq_dbt_training:
    staging:
      +materialized: "view"
      +schema: 'dna_foundry_curated_dataset'
    marts:
      +materialized: "table"
      +schema: 'dna_foundry_confirmed_dataset'

# Configure snapshots
# Full documentation: https://docs.getdbt.com/reference/snapshot-configs    

snapshots:
  bq_dbt_training:
    greg_snapshot_orders:
      +target_schema: 'dna_foundry_curated_dataset'
      +strategy: 'timestamp'
      +unique_key: 'ID'
      +updated_at: '_etl_loaded_at'
      +invalidate_hard_deletes: True
